export const cities = [
  'Angra dos Reis',
  'Niterói',
  'Petrópolis',
  'Nova Iguaçu',
  'Macaé',
  'Rio de Janeiro',
  'Nova Friburgo',
  'São João da Barra',
  'Volta Redonda',
  'Duque de Caxias',
  'Tanguá',
  'Quatis',
  'Magé',
  'Mesquita',
  'São João de Meriti',
  'Campos dos Goytacazes',
  'Itaguaí',
  'Araruama',
  'Valença',
  'Silva Jardim',
  'Iguaba Grande',
  'Saquarema',
  'Rio das Ostras',
  'Santa Maria Madalena',
  'Paraíba do Sul',
  'Porto Real',
  'Itaperuna',
  'Bom Jardim',
  'Miguel Pereira',
  'Miracema',
  'Paty do Alferez',
  'Queimados',
  'Maricá',
  'Pinheiral',
  'Quissamã',
  'Rio Bonito',
  'São Francisco de Itabapoana',
  'Vassouras',
  'Resende',
  'São Pedro da Aldeia',
  'Itaboraí',
  'Engenheiro Paulo de Frontin',
  'Teresópolis',
  'Cachoeiras de Macacu',
  'Trajano de Moraes',
  'Itaocara',
] as const;
